# Generated by Django 4.0.3 on 2022-04-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
