# Generated by Django 4.0.3 on 2022-04-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github_link',
            field=models.CharField(default='https://github.com', max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.CharField(default='https://youtube.com', max_length=255),
        ),
    ]
